config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  # scope '(:locale)', locale: /fr/, default:  do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/, defaults: {locale: "en"} do
    root to: 'pages#home'

    devise_for :users, controllers: { registrations: 'registrations', confirmations: 'confirmations' }
    get 'confirm', to: 'pages#confirm'

    get 'about', to: 'pages#about'
    get 'contact', to: 'pages#contact'

    post '/subscribe', to: 'pages#subscribe'


    # Routes for core user side
    resources :users, only: [ :show, :edit, :update ] do

      # User Pages
      get 'profile', to: 'users#profile'
      get 'digital', to: 'users#digital'
      get 'children', to: 'users#children'
      get 'unlock', to: 'users#unlock'
      post 'unlock_data', to: 'users#unlock_data'
      resources :videos
      resources :call_to_action, controller: 'call_to_action', only: [:index, :new, :create, :edit, :update, :destroy]

      resources :notes
      resources :photos
      resources :references

      # Assignee Pages
      resources :assignees do
        get 'profile', to: 'assignees#profile'
        resources :notes
        resources :photos
        resources :references
      end

      # Approver Pages
      resources :approvers, controller: 'assignees', type: 'Approver' do
        # get 'notes', to: 'assignees#notes'
        # get 'references', to: 'assignees#references'
        # get 'photos', to: 'assignees#photos'
        # get 'video', to: 'assignees#video'
        get 'profile', to: 'assignees#profile'
        resources :notes, only: [:index, :new, :create, :edit, :update, :destroy]
        resources :photos, only: [:index, :show, :new, :create, :edit, :update, :destroy]
        resources :references, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      end

      # Guardian Pages
      resources :guardians, controller: 'assignees', type: 'Guardian' do
        get 'profile', to: 'assignees#profile'
        resources :notes, only: [:index, :new, :create, :edit, :update, :destroy]
        resources :photos, only: [:index, :show, :new, :create, :edit, :update, :destroy]
        resources :references, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      end

      # Recipient Pages
      resources :recipients, controller: 'assignees', type: 'Recipient' do
        get 'profile', to: 'assignees#profile'
        resources :notes, only: [:index, :new, :create, :edit, :update, :destroy]
        resources :photos, only: [:index, :show, :new, :create, :edit, :update, :destroy]
        resources :references, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      end

      # Routes for wizard sign-up
      resources :after_sign_up
    end
  end
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:edit, :update, :destroy]
  # before_action :set_assignee, only: [:new, :create, :edit, :update, :destroy]

  def index
    @notes = policy_scope(Note)
    @note = Note.new
    @assignee = Assignee.find(params[:approver_id] || params[:guardian_id] || params[:recipient_id] || params[:assignee_id]) if params[:approver_id] || params[:guardian_id] || params[:recipient_id] || params[:assignee_id]
  end

  def new
    @note = Note.new
    authorize @note
    @assignee = Assignee.find(params[:assignee_id]) if params[:assignee_id]
  end

  def create
    @note = current_user.notes.create!(note_params)
    authorize @note
    if @note.save
      if @note.assignee_id
        redirect_to user_assignee_path(current_user, @note.assignee_id), notice: 'Note was successfully created.'
      else
        redirect_to user_path(current_user), notice: 'Note was successfully created.'
      end
    else
      render :new
    end
  end

  def edit
    authorize @note
  end

  def update
    authorize @note
    if @note.update(note_params)
      if @note.assignee_id
        redirect_to user_assignee_path(current_user, @note.assignee_id), notice: 'Note was successfully updated.'
      else
        redirect_to user_path(current_user), notice: 'Note was successfully updated.'
      end
    else
      render :edit
    end
  end

  def destroy
    authorize @note
    @note.destroy
    if @note.assignee_id
      redirect_to user_assignee_path(current_user, @note.assignee_id), notice: 'Note was successfully deleted.'
    else
      redirect_to user_path(current_user), notice: 'Note was successfully deleted.'
    end
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  # def set_assignee
  #   @assignee = Assignee.find(params[:assignee_id] || params[:guardian_id] || params[:recipient_id])
  # end

  def note_params
    params.require(:note).permit(:title, :content, :assignee_id)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_assignee_index.html.erb
<div class="container">
  <br>

  <% if !@assignee.notes.empty? %>
    <div class="header-box padding-15">
      <h2><%= t('Notes Library') %></h2>
      <%= link_to t("Add Note"), new_user_assignee_note_path(I18n.locale, current_user.id, @assignee, @note), remote: true, class: "btn orange-button", id: "add-note" %>
    </div>

    <div class="blue-box detail-box side-margin-small top-margin">
      <p><%= t('note description html') %></p>
    </div>

    <div class="col-xs-12 col-md-6 invisible">
      <div class="note-card">
        <div class="note-form" id="new-note-form"></div>
      </div>
    </div>

    <% @assignee.notes.reverse.each do |note| %>
      <div class="col-xs-12 col-sm-6">
        <div class="note-card">
          <div class="card-buttons">
            <%= link_to edit_user_note_path(current_user, note.id), remote: true do %>
              <i class="fa fa-pencil" aria-hidden="true"> </i>
            <% end %>
            <%= link_to user_note_path(current_user, note.id), data: {confirm: t('Are you sure')}, method: :delete do %>
              <i class="fa fa-trash" aria-hidden="true"></i>
            <% end %>
          </div>
          <div class="note-spacing" id="assignee-note-<%= note.id %>">
            <div class="note-title">
              <h4><strong><%= note.title %></strong></h4>
              <h5><strong>For:</strong> <%= Assignee.find(note.assignee_id).first_name %></h5>
            </div>
            <hr>
            <br>
            <div class="card-content card-overflow">
              <p><%= note.content %></p>
            </div>
          </div>
          <div class="note-form" id="edit-note-form-<%= note.id %>"></div>
        </div>
      </div>
    <% end %>

  <% else %>

    <div class="side-margin white-text">
      <h2><%= t('Notes') %></h2>

      <div class="blue-box">
        <p><%= t('note description html') %></p>
      </div>
    </div>

    <div class="grey-box">
      <h5><strong><%= t('not added notes') %></strong></h5>
      <p><%= t('please use form below') %></p>
      <%= simple_form_for([@user, @assignee, @note]) do |f| %>
        <%= f.hidden_field :assignee_id, value: @assignee.id %>
        <%= f.input :title, label: t('Title') %>
        <%= f.input :content, label: t('Content') %>
        <div class="submit-button text-center">
          <%= f.button :submit, t("Create"), class: "btn purple-button" %>
        </div>
      <% end %>
    </div>

  <% end %>
</div>

app/views/notes/_edit_form.html.erb
<%= simple_form_for [current_user, @assignee, @note] do |f| %>
  <h4>Edit note:</h4>
  <%= f.hidden_field :assignee_id, value: params[:assignee_id] %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.button :submit, class: "purple-button pull-right" %>
<% end %>

app/views/notes/_form.html.erb
<%= simple_form_for [current_user, @assignee, @note] do |f| %>
  <h4>New note:</h4>
  <%= f.hidden_field :assignee_id, value: params[:assignee_id] %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.button :submit, class: "purple-button pull-right" %>
<% end %>

app/views/notes/_new_form.html.erb
<%= simple_form_for [current_user, @assignee, @note] do |f| %>
  <h4>New note:</h4>
  <%= f.hidden_field :assignee_id, value: params[:assignee_id] %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.button :submit, class: "purple-button pull-right", id: "create-note" %>
<% end %>

app/views/notes/_user_index.html.erb
<div class="container">
  <br>

  <% if !@notes.empty? %>
    <div class="header-box padding-15">
      <h2><%= t('Notes Library') %></h2>
      <%= link_to t("Add Note"), new_user_note_path([I18n.locale, current_user, @note]), remote: true, class: "btn orange-button", id: "add-note" %>
    </div>

    <div class="blue-box detail-box side-margin-small top-margin">
      <p><%= t('note description html') %></p>
    </div>

    <div class="col-xs-12 col-md-6 invisible">
      <div class="note-card">
        <div class="note-form" id="new-note-form"></div>
      </div>
    </div>

    <% @user.notes.reverse.each do |note| %>
      <div class="col-xs-12 col-sm-6">
        <div class="note-card">
          <div class="card-buttons">
            <% if note.assignee_id? %>
              <%= link_to edit_user_assignee_note_path(current_user, note.assignee_id, note.id), remote: true do %>
                <i class="fa fa-pencil" aria-hidden="true"> </i>
              <% end %>
              <%= link_to user_assignee_note_path(current_user, note.assignee_id, note.id), data: {confirm: t('Are you sure')}, method: :delete do %>
                <i class="fa fa-trash" aria-hidden="true"></i>
              <% end %>
            <% else %>
              <%= link_to edit_user_note_path(current_user, note.id), remote: true do %>
                <i class="fa fa-pencil" aria-hidden="true"> </i>
              <% end %>
              <%= link_to user_note_path(current_user, note.id), data: {confirm: t('Are you sure')}, method: :delete do %>
                <i class="fa fa-trash" aria-hidden="true"></i>
              <% end %>
            <% end %>
          </div>
          <div class="note-spacing" id="assignee-note-<%= note.id %>">
            <div class="note-title">
              <h4><strong><%= note.title %></strong></h4>
              <h5><strong>For:</strong> <%= note.assignee_id ? Assignee.find(note.assignee_id).first_name : 'Everyone' %></h5>
            </div>
            <hr>
            <br>
            <div class="card-content card-overflow">
              <p><%= note.content %></p>
            </div>
          </div>
          <div class="note-form" id="edit-note-form-<%= note.id %>"></div>
        </div>
      </div>
    <% end %>

  <% else %>

    <div class="side-margin white-text">
      <h2><%= t('Notes') %></h2>

      <div class="blue-box">
        <p><%= t('note description html') %></p>
      </div>
    </div>

    <div class="grey-box">
      <h5><strong><%= t('not added notes') %></strong></h5>
      <p><%= t('please use form below') %></p>
      <%= simple_form_for([@user, @note]) do |f| %>
        <%= f.input :title, label: t('Title') %>
        <%= f.input :content, label: t('Content') %>
        <div class="submit-button text-center">
          <%= f.button :submit, t("Create"), class: "btn purple-button" %>
        </div>
      <% end %>
    </div>

  <% end %>
</div>

app/views/notes/create.js.erb
$("#create-note").on("click", function() {
  request = void 0;
  request = $.ajax({
    url: "/articles/create/?title=acme&text=123 Carrot Street"
  });
  request.done(function(data, textStatus, jqXHR) {
    console.log(data);
  });
  request.error(function(jqXHR, textStatus, errorThrown) {
    alert("AJAX Error:" + textStatus);
  });
});

app/views/notes/edit.js.erb
$('#assignee-note-<%= @note.id %>').empty().removeClass('note-spacing')
$('#edit-note-form-<%= @note.id %>').parent().removeClass('hidden');
$('#edit-note-form-<%= @note.id %>').removeClass('hidden');
$('#edit-note-form-<%= @note.id %>').html("<%= j (render 'notes/edit_form')%>");

app/views/notes/index.html.erb
<% content_for(:navbar) do %>
  <%= render 'shared/navbar' %>
<% end %>

<% if @assignee %>
  <%= render 'notes/assignee_index' %>
<% else %>
  <%= render 'notes/user_index' %>
<% end %>

app/views/notes/new.js.erb
$('#new-note-form').parent().parent().removeClass('invisible');
$('#new-note-form').parent().removeClass('hidden');
$('#new-note-form').removeClass('hidden');
$('#new-note-form').html("<%= j render 'notes/new_form' %>");