config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  # scope '(:locale)', locale: /fr/, default:  do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/, defaults: {locale: "en"} do
    root to: 'pages#home'

    devise_for :users, controllers: { registrations: 'registrations', confirmations: 'confirmations' }
    get 'confirm', to: 'pages#confirm'

    get 'about', to: 'pages#about'
    get 'contact', to: 'pages#contact'

    post '/subscribe', to: 'pages#subscribe'


    # Routes for core user side
    resources :users, only: [ :show, :edit, :update ] do

      # User Pages
      get 'profile', to: 'users#profile'
      get 'digital', to: 'users#digital'
      get 'children', to: 'users#children'
      get 'unlock', to: 'users#unlock'
      post 'unlock_data', to: 'users#unlock_data'
      resources :videos
      resources :call_to_action, controller: 'call_to_action', only: [:index, :new, :create, :edit, :update, :destroy]

      resources :notes
      resources :photos
      resources :references

      # Assignee Pages
      resources :assignees do
        get 'profile', to: 'assignees#profile'
        resources :notes
        resources :photos
        resources :references
      end

      # Approver Pages
      resources :approvers, controller: 'assignees', type: 'Approver' do
        # get 'notes', to: 'assignees#notes'
        # get 'references', to: 'assignees#references'
        # get 'photos', to: 'assignees#photos'
        # get 'video', to: 'assignees#video'
        get 'profile', to: 'assignees#profile'
        resources :notes, only: [:index, :new, :create, :edit, :update, :destroy]
        resources :photos, only: [:index, :show, :new, :create, :edit, :update, :destroy]
        resources :references, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      end

      # Guardian Pages
      resources :guardians, controller: 'assignees', type: 'Guardian' do
        get 'profile', to: 'assignees#profile'
        resources :notes, only: [:index, :new, :create, :edit, :update, :destroy]
        resources :photos, only: [:index, :show, :new, :create, :edit, :update, :destroy]
        resources :references, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      end

      # Recipient Pages
      resources :recipients, controller: 'assignees', type: 'Recipient' do
        get 'profile', to: 'assignees#profile'
        resources :notes, only: [:index, :new, :create, :edit, :update, :destroy]
        resources :photos, only: [:index, :show, :new, :create, :edit, :update, :destroy]
        resources :references, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      end

      # Routes for wizard sign-up
      resources :after_sign_up
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_attachment :profile_picture

  has_many :assignees, dependent: :destroy
    has_many :guardians, dependent: :destroy
    has_many :recipients, dependent: :destroy
    has_many :approvers, dependent: :destroy
  has_many :proofs, dependent: :destroy
  has_many :notes, dependent: :destroy
  has_many :references, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :videos, dependent: :destroy
  has_one :call_to_action, dependent: :destroy

  # validates :email, uniqueness: true
  validates :title, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  accepts_nested_attributes_for :assignees

  def details_completed?
    true if first_name && last_name && profile_picture && citizenship && date_of_birth && email && phone_number && address_line_1 && address_line_2 && city && postcode && country
  end

  def full_name
    middle_name ? first_name + " " + middle_name + " " + last_name : first_name + " " + last_name
  end

  def name_surname
    first_name + " " + last_name
  end

  # Relationship Methods
  def partner
    recipients.where('relationship = ?', 'Partner').first
  end

  def children
    recipients.where('relationship = ?', 'Child')
  end

  def show_other
    recipients.where(['relationship != ? AND relationship != ?', 'Partner', 'Child'])
  end

  def show_other_family
    recipients.where('relationship != ? AND relationship != ? AND relationship != ?',
     'Friend', 'Partner', 'Child')
  end

  def show_mother
    recipients.where('relationship = ?', 'Mother')
  end

  def show_friends
    recipients.where('relationship = ?', 'Friend')
  end

  private

  # Data Unlock
  def self.send_unlock_email(user, recipients)
    UserMailer.unlock(user, recipients).deliver_now
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :set_user_id, only: [:profile, :children, :unlock, :unlock_data]

  def show
    authorize @user
    # @proofs = policy_scope(Proof)
    # @proof = Proof.new
  end

  def edit
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def profile
    authorize @user
  end

  def digital
    authorize @user
  end

  def proof
    authorize @user
  end

  def notes
    authorize @user
  end

  def children
    authorize @user
  end

  def unlock
    authorize @user
  end

  def unlock_data
    authorize @user
    @recipients = params[:user][:recipients]
    User.send_unlock_email(@user, @recipients)
    # if email is sent successfully
    @user.data_unlocked = true
    @user.save
    redirect_to user_unlock_path(@user)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def set_user_id
    @user = User.find(params[:user_id])
  end

  def user_params
    params.require(:user).permit(:email, :title, :first_name, :middle_name, :last_name,
      :citizenship, :date_of_birth, :phone_number, :gender,
      :address_line_1, :address_line_2, :city, :country, :postcode,
      :latitude, :longitude, :profile_picture, :data_unlocked)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/admin.html.erb
<div class="grey-box">
  <h2>Admin References</h2>

  <div class="blue-box">
    <p>Here you can administrative documents and data that...</p>
  </div>

  <h3>My References</h3>
  <% @user.references.each do |reference| %>
    <div class="detail-box">
      <div class="detail">
        <%= reference.title %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/call_to_action.html.erb
<div class="grey-box">
  <h2>Call to Action</h2>

  <%= image_tag("user.png", class: "avatar-large") %>
  <p>John Hartaway</p>

  <div class="blue-box">
    <p>In this section you must specify <strong>the event that will kick off the release of your data if you are not in a position to access it.</strong></p>
    <p>This call to action will require <strong>the approval of at least three of your approvers.</strong> An approver can be a legal person or someone you know.</p>
    <p>Once the quroum of approvers have confirmed your situation, we release your data to those concerned.</p>
    <p>The data attached to your call of action will be stored in a secure blockchain for authenticity purposes. For example: your proof of residency in case of Brexit.</p>
    <p><strong>Guardians</strong> are trusted people that will either testify to your situation or will take over some of your existing responsibilities.</p>
  </div>

  <hr>

  <div class="detail-box">
    <div class="detail">
      <p><strong>My Call to Action</strong></p>
      <p>Brexit Dropdown</p>
    </div>
    <div class="detail">
      <p><strong>Authenticity Requirement:</strong></p>
      <p>Requirements Dropdown</p>
    </div>
    <div class="detail">
      <p>Add</p>
      <p>Delete</p>
    </div>
  </div>
</div>

app/views/users/children.html.erb
<% content_for(:navbar) do %>
  <%= render 'shared/navbar' %>
<% end %>

<div class="dashboard-box" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.2) 50%), url(<%= asset_path('background.jpg') %>)">
  <div id="tab-content">
    <div class="container">
      <br>
      <div class="header-box">
        <h2><%= t('My Children') %></h2>
        <%= link_to t("Add Child"), new_user_assignee_path(I18n.locale, current_user, 'Child'), class: "btn orange-button" %>
      </div>

      <div class="assignees">
        <div class="row">
          <% @user.assignees.where('relationship = ?', 'Child').each do |assignee| %>
            <div class="col-xs-12 col-md-6 col-lg-4">
              <div class="card">
                <div class="card-buttons child-buttons">
                  <%= link_to user_assignee_path(current_user, assignee.id), data: {confirm: t('Are you sure')}, method: :delete do %>
                    <i class="fa fa-trash" aria-hidden="true"></i>
                  <% end %>
                </div>
                <%= link_to user_assignee_path(current_user, assignee.id) do %>
                  <% if assignee.profile_picture %>
                    <%= cl_image_tag(assignee.profile_picture.path, transformation: [{width: 100, height: 100, gravity: "face", radius: "max", crop: "fill"}], class: "avatar-card push-right") %>
                  <% elsif assignee.title == "Mrs" || assignee.title == "Ms" %>
                    <%= image_tag('girl.png', class: "index-icon") %>
                  <% else %>
                    <%= image_tag('boy.png', class: "index-icon") %>
                  <% end %>
                  <div class="card-description">
                    <%= link_to user_assignee_path(current_user, assignee.id) do %>
                      <h5 class="black-text"><strong><%= assignee.name_surname %></strong></h5>
                      <h7 class="black-text"><%= assignee.try(:relationship) %></h7>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/digital.html.erb
<br><br>

<div class="container profile-cards">

  <div class="col-xs-12 col-sm-6">
    <div class="alt-card black-links">
      <i class="fa fa-question-circle card-info" aria-hidden="true"><span class="info-tooltip"><%= t('notes infotip') %></span></i>

      <h4 class="profile-card-link"><%= link_to t("Notes"), user_notes_path(current_user), class: "note-link" %><span class="card-tooltip"><%= t('notes tooltip') %></span></h4>
      <hr>
      <div class="card-content card-overflow">
        <% if !@user.notes.empty? %>

          <% @user.notes.reverse.each do |note| %>
            <p><%= note.title %> - <strong><%= note.assignee_id ? Assignee.find(note.assignee_id).first_name : 'Everyone' %></strong></p>
          <% end %>

        <% else %>

          <p><%= link_to t('assign notes'), user_notes_path(current_user), class: "proof-card" %></p>

        <% end %>
      </div>
    </div>
  </div>

  <div class="col-xs-12 col-sm-6">
    <div class="alt-card black-links">
      <i class="fa fa-question-circle card-info" aria-hidden="true"><span class="info-tooltip"><%= t('photos infotip') %></span></i>

      <h4 class="profile-card-link"><%= link_to t("Photos"), user_photos_path(current_user), class: "photo-link" %><span class="card-tooltip"><%= t('photos tooltip') %></span></h4>
      <hr>
      <div class="card-content card-overflow">
        <% if !@user.photos.empty? %>

          <% @user.photos.reverse.each do |photo| %>
            <p><%= photo.title %> - <strong><%= photo.assignee_id ? Assignee.find(photo.assignee_id).first_name : 'Everyone' %></strong></p>
          <% end %>

        <% else %>

          <p><%= link_to t('assign photos'), user_photos_path(current_user), class: "proof-card" %></p>

        <% end %>
      </div>
    </div>
  </div>

  <div class="col-xs-12 col-sm-6">
    <div class="alt-card black-links">
      <i class="fa fa-question-circle card-info" aria-hidden="true"><span class="info-tooltip"><%= t('references infotip') %></span></i>

      <h4 class="profile-card-link"><%= link_to t("Admin References"), user_references_path(current_user), class: "reference-link" %><span class="card-tooltip"><%= t('references tooltip') %></span></h4>
      <hr>
      <div class="card-content card-overflow">
        <% if !@user.references.empty? %>

          <% @user.references.reverse.each do |reference| %>
            <p><%= reference.title %> - <strong><%= reference.assignee_id ? Assignee.find(reference.assignee_id).first_name : 'Everyone' %></strong></p>
          <% end %>

        <% else %>

          <p><%= link_to t('assign references'), user_references_path(current_user), class: "proof-card" %></p>

        <% end %>
      </div>
    </div>
  </div>

  <div class="col-xs-12 col-sm-6">
    <div class="alt-card black-links">
      <i class="fa fa-question-circle card-info" aria-hidden="true"><span class="info-tooltip"><%= t('videos infotip') %></span></i>

      <h4 class="profile-card-link"><%= link_to t("Videos"), '#', class: "video-link" %><span class="card-tooltip"><%= t('videos tooltip') %></span></h4>
      <hr>
      <div class="card-content card-overflow">
        <%# if !@user.videos.empty? %>

          <%# @user.videos.reverse.each do |video| %>
            <p><%# video.title %></p>
          <%# end %>

        <%# else %>

          <p><%# link_to t('assign videos'), user_notes_path(current_user), class: "proof-card" %></p>

        <%# end %>
      </div>
    </div>
  </div>
</div>

<br>

<% content_for(:after_js) do %>
  <script>
    // Clicking on card headings switches tab
      $('.reference-link').click(function(e){
        e.preventDefault();
        $('.sidebar-tabs').children().removeClass("active");
        $('#admin-references-sidebar-tab').addClass("active");
        $.ajax({
            type: "GET",
            url: <%= @user.id %> + "/references",
            data: { },
            success: function(data){
                $('#tab-content').empty().html(data);
            }
        });
      });
      $('.note-link').click(function(e){
        e.preventDefault();
        $('.sidebar-tabs').children().removeClass("active");
        $('#notes-sidebar-tab').addClass("active");
        $.ajax({
            type: "GET",
            url: <%= @user.id %> + "/notes",
            data: { },
            success: function(data){
                $('#tab-content').empty().html(data);
            }
        });
      });
      $('.photo-link').click(function(e){
        e.preventDefault();
        $('.sidebar-tabs').children().removeClass("active");
        $('#photo-library-sidebar-tab').addClass("active");
        $.ajax({
            type: "GET",
            url: <%= @user.id %> + "/photos",
            data: { },
            success: function(data){
                $('#tab-content').empty().html(data);
            }
        });
      });
      // $('.video-link').click(function(e){
      //   e.preventDefault();
      //   $('.sidebar-tabs').children().removeClass("active");
      //   $('#video-library-sidebar-tab').addClass("active");
      //   $.ajax({
      //       type: "GET",
      //       url: <%= @user.id %> + "/videos",
      //       data: { },
      //       success: function(data){
      //           $('#tab-content').empty().html(data);
      //       }
      //   });
      // });
  </script>
<% end %>

app/views/users/profile.html.erb
<br><br>

<div class="container profile-cards">

  <div class="col-xs-12 col-sm-6 col-md-4">
    <div class="alt-card black-links">
      <i class="fa fa-question-circle card-info" aria-hidden="true"><span class="info-tooltip"><%= t('my details infotip') %></span></i>

      <% unless @user.details_completed? %>
        <i class="fa fa-exclamation-circle warning-circle" aria-hidden="true"><span class="warning-tooltip"><%= t('details incomplete tooltip') %></span></i>

      <% end %>
      <h4 class="profile-card-link"><%= link_to t('My Details'), user_path(current_user), class: "details-link" %><span class="card-tooltip"><%= t('my details tooltip') %></span></h4>
      <hr>
      <div class="card-content card-overflow">
        <%= link_to user_path(current_user) do %>
          <p class="name-tag"><strong><%= @user.try(:name_surname) %></strong></p>
        <% end %>

        <% if @user.citizenship %>
          <p><%= @user.citizenship + " " + t('Citizen') %></p>
        <% else %>
          <p class="notice-text"><%= t('citizenship required') %></p>
        <% end %>

        <% if @user.date_of_birth && @user.date_of_birth != "" %>
          <p><span class="category-tag"><%= t('DoB') %></span><%= ": " + @user.date_of_birth %></p>
        <% else %>
          <p class="notice-text"><%= t('date of birth required') %></p>
        <% end %>

        <p><span class="category-tag"><%= t('Email')%></span><%= ": " + @user.email %></p>

        <% if @user.phone_number && @user.phone_number != "" %>
          <p><span class="category-tag"><%= t('Phone Number') %></span><%= ": " + @user.phone_number %></p>
        <% else %>
          <p class="notice-text"><%= t('phone number required') %></p>
        <% end %>

        <% if @user.address_line_1 && @user.address_line_1 != "" %>
          <p><span class="category-tag"><%= t('Address') %></span><%= ": " + @user.address_line_1 %><%= ", " + @user.address_line_2 if @user.address_line_2 %></p>
          <p><%= @user.try(:city) %><%= ", " + @user.postcode if @user.postcode %><%= ", " + @user.country if @user.country %></p>
        <% else %>
          <p class="notice-text"><%= t('address required') %></p>
        <% end %>

        <br>
      </div>
    </div>
  </div>

  <div class="col-xs-12 col-sm-6 col-md-4">
    <div class="alt-card black-links">
      <i class="fa fa-question-circle card-info" aria-hidden="true"><span class="info-tooltip"><%= t('call to action infotip') %></span></i>

      <h4 class="profile-card-link"><%= link_to t("My Call to Action"), user_call_to_action_index_path(current_user), class: "call-to-action-link" %><span class="card-tooltip"><%= t('call to action tooltip') %></span></h4>
      <hr>
      <div class="card-content card-overflow">
        <% if @user.call_to_action %>

          <%= @user.call_to_action.event %>

        <% else %>

          <p><%= link_to t('assign call_to_action'), new_user_call_to_action_path(I18n.locale, current_user, @call_to_action), class: "call-to-action-card" %></p>

        <% end %>
      </div>
    </div>
  </div>

  <div class="col-xs-12 col-sm-6 col-md-4">
    <% if @user.assignees.where('relationship = ?', 'Partner').last %>

      <div class="alt-card black-links">
        <i class="fa fa-question-circle card-info" aria-hidden="true"><span class="info-tooltip"><%= t('partner infotip') %></span></i>

        <% @user.assignees.where('relationship = ?', 'Partner').each do |partner| %>
          <% unless partner.details_completed? %>
            <i class="fa fa-exclamation-circle warning-circle" aria-hidden="true"><span class="warning-tooltip"><%= t('details incomplete tooltip') %></span></i>
          <% end %>
          <h4 class="profile-card-link"><%= link_to t("My Partner"), user_assignee_path(@user, partner) , class: "partner-link" %><span class="card-tooltip"><%= t('partner tooltip') %></span></h4>
          <hr>
          <div class="card-content card-overflow">
            <p class="name-tag"><strong><%= link_to partner.name_surname, user_assignee_path(@user, partner) %></strong></p>
            <p><%= partner.phone_number %></p>
          </div>
        <% end %>

        <!-- My Children -->
        <div class="relative max-width">
          <i class="fa fa-question-circle card-info" aria-hidden="true"><span class="info-tooltip"><%= t('children infotip') %></span></i>
        </div>
        <h4 class="profile-card-link"><%= link_to t("My Children"),user_children_path(current_user), class: "recipient-link" %><span class="card-tooltip"><%= t('children tooltip') %></span></h4>
        <hr>
        <div class="card-content card-overflow">
          <% if !@user.children.empty? %>

            <% @user.assignees.where('relationship = ?', 'Child').each do |child| %>
              <% unless child.details_completed? %>
                <i class="fa fa-exclamation-circle warning-circle" aria-hidden="true"><span class="warning-tooltip"><%= t('details incomplete tooltip') %></span></i>
              <% end %>
              <p class="name-tag"><strong><%= link_to child.try(:name_surname), user_assignee_path(@user, child) %></strong></p>
              <p><%= child.try(:phone_number) %></p>
            <% end %>

          <% else %>

            <p><%= link_to t('assign children'), new_user_assignee_path(I18n.locale, current_user, 'Child'), class: "proof-card" %></p>
          <% end %>
        </div>
      </div>

    <% else %>

      <div class="alt-card black-links">
        <i class="fa fa-question-circle card-info" aria-hidden="true"><span class="info-tooltip"><%= t('partner infotip') %></span></i>

        <h4 class="profile-card-link"><%= link_to t("My Partner"), "#" , class: "partner-link" %><span class="card-tooltip"><%= t('partner tooltip') %></span></h4>
        <hr>
        <div class="card-content card-overflow">
          <p><%= link_to t("assign a partner"), new_user_assignee_path(I18n.locale, current_user, 'Recipient', relationship: 'Partner'), class: "proof-card" %></p>
        </div>

        <!-- My Children -->
        <div class="relative max-width">
          <i class="fa fa-question-circle card-info" aria-hidden="true"><span class="info-tooltip"><%= t('children infotip') %></span></i>
        </div>

        <h4 class="profile-card-link"><%= link_to t("My Children"),user_children_path(current_user), class: "recipient-link" %><span class="card-tooltip"><%= t('children tooltip') %></span></h4>
        <hr>
        <div class="card-content card-overflow">
          <% if !@user.children.empty? %>

            <% @user.assignees.where('relationship = ?', 'Child').each do |child| %>
              <% unless child.details_completed? %>
                <i class="fa fa-exclamation-circle warning-circle" aria-hidden="true"><span class="warning-tooltip"><%= t('details incomplete tooltip') %></span></i>
              <% end %>
              <p class="name-tag"><strong><%= link_to child.try(:name_surname), user_assignee_path(@user, child) %></strong></p>
              <p><%= child.try(:phone_number) %></p>
            <% end %>

          <% else %>

            <p><%= link_to t('assign children'), new_user_assignee_path(I18n.locale, current_user, 'Child'), class: "proof-card" %></p>
          <% end %>
        </div>
      </div>

    <% end %>
  </div>

  <div class="col-xs-12 col-sm-6 col-md-4">
    <div class="alt-card black-links">
      <i class="fa fa-question-circle card-info" aria-hidden="true"><span class="info-tooltip"><%= t('guardian infotip') %></span></i>

      <h4 class="profile-card-link"><%= link_to t("My Guardians"), user_guardians_path(current_user), class: "guardian-link" %><span class="card-tooltip"><%= t('guardian tooltip') %></span></h4>
      <hr>
      <div class="card-content card-overflow">
        <% if !@user.guardians.empty? %>

          <% @user.guardians.each do |guardian| %>
            <% unless guardian.details_completed? %>
              <i class="fa fa-exclamation-circle warning-circle" aria-hidden="true"><span class="warning-tooltip"><%= t('details incomplete tooltip') %></span></i>
            <% end %>
            <p class="name-tag"><strong><%= link_to guardian.name_surname, user_assignee_path(@user, guardian) %></strong></p>
            <p><%= guardian.try(:phone_number) %></p>
          <% end %>

        <% else %>

          <p><%= link_to t('assign guardians'), new_user_assignee_path(I18n.locale, current_user, 'Guardian'), class: "proof-card" %></p>

        <% end %>
      </div>
    </div>
  </div>

  <div class="col-xs-12 col-sm-6 col-md-4">
    <div class="alt-card black-links">
      <i class="fa fa-question-circle card-info" aria-hidden="true"><span class="info-tooltip"><%= t('approver infotip') %></span></i>

      <h4 class="profile-card-link"><%= link_to t("My Approvers"), user_approvers_path(current_user), class: "approver-link" %><span class="card-tooltip"><%= t('approver tooltip') %></span></h4>
      <hr>
      <div class="card-content card-overflow">
        <% if !@user.approvers.empty? %>

          <% @user.approvers.each do |approver| %>
            <% unless approver.details_completed? %>
              <i class="fa fa-exclamation-circle warning-circle" aria-hidden="true"><span class="warning-tooltip"><%= t('details incomplete tooltip') %></span></i>
            <% end %>
            <p class="name-tag"><strong><%= link_to approver.name_surname, user_assignee_path(@user, approver) %></strong></p>
            <p><%= approver.try(:phone_number) %></p>
          <% end %>

        <% else %>

          <p><%= link_to t('assign approvers'), new_user_assignee_path(I18n.locale, current_user, 'Approver'), class: "proof-card" %></p>

        <% end %>
      </div>
    </div>
  </div>

  <div class="col-xs-12 col-sm-6 col-md-4">
    <div class="alt-card black-links">
      <i class="fa fa-question-circle card-info" aria-hidden="true"><span class="info-tooltip"><%= t('recipient infotip') %></span></i>

      <h4 class="profile-card-link"><%= link_to t("Other Friends & Family"),user_assignees_path(current_user), class: "recipient-link" %><span class="card-tooltip"><%= t('recipient tooltip') %></span></h4>
      <hr>
      <div class="card-content card-overflow">
        <% if !@user.show_other.empty? %>

          <% @user.show_other.each do |recipient| %>
            <% unless recipient.details_completed? %>
              <i class="fa fa-exclamation-circle warning-circle" aria-hidden="true"><span class="warning-tooltip"><%= t('details incomplete tooltip') %></span></i>
            <% end %>
            <p class="name-tag"><strong><%= link_to recipient.try(:name_surname), user_assignee_path(@user, recipient) %></strong></p>
            <p><%= recipient.try(:phone_number) %></p>
          <% end %>

        <% else %>

          <p><%= link_to t('assign recipients'), new_user_assignee_path(I18n.locale, current_user, 'Other'), class: "proof-card" %></p>

        <% end %>
      </div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <script>
    // Clicking on card headings switches tab
      $('.details-link').click(function(e){
        e.preventDefault();
        $('.sidebar-tabs').children().removeClass("active");
        $('#personal-details-sidebar-tab').addClass("active");
        $.ajax({
            type: "GET",
            url: <%= @user.id %> + "/edit",
            data: { },
            success: function(data){
                $('#tab-content').empty().html(data);
            }
        });
      });
      $('.call-to-action-link').click(function(e){
        e.preventDefault();
        $('.sidebar-tabs').children().removeClass("active");
        $('#call-to-action-sidebar-tab').addClass("active");
        $.ajax({
            type: "GET",
            url: <%= @user.id %> + "/call_to_action",
            data: { },
            success: function(data){
                $('#tab-content').empty().html(data);
            }
        });
      });
  </script>
<% end %>

app/views/users/show.html.erb
<% content_for(:navbar) do %>
  <%= render 'shared/navbar' %>
<% end %>

<% content_for(:sidebar) do %>
  <%= render 'shared/sidebars/sidebar_core' %>
<% end %>

<div class="dashboard-box" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.2) 50%), url(<%= asset_path('background.jpg') %>)">
  <div id="tab-content">
      <%= render file: 'users/profile' %>
  </div>
</div>

<!-- <div class="dashboard-box">
  <div id="tab-content">
    <div class="0" id="my-profile-content">
      <%# render file: 'users/profile' %>
    </div>

    <div class="2 hidden" id="call_to_action-content">
      <%# render file: 'call_to_action/index' %>
    </div>

    <div class="4 hidden" id="personal-details-content">
      <%# render file: 'users/edit' %>
    </div>

    <div class="6 hidden" id="guardian-content">
      <%# render 'users/profile/guardians' %>
    </div>

    <div class="8 hidden" id="approver-content">
      <%# render 'users/profile/approvers' %>
    </div>

    <div class="10 hidden" id="family-and-friends-content">
      <%# render 'users/profile/family_and_friends' %>
    </div>

    <div class="12 hidden" id="my-digital-assets-content">
      <%# render file: 'users/digital' %>
    </div>

    <div class="14 hidden" id="proof-of-residency-content">
      <%# render file: 'users/proof' %>
    </div>

    <div class="16 hidden" id="admin-references-content">
      <%# render 'users/digital_assets/admin_references' %>
    </div>

    <div class="18 hidden" id="notes-content">
      <%# render file: 'users/notes' %>
    </div>

    <div class="20 hidden" id="photo-library-content">
      <%# render file: 'users/photos' %>
    </div>

    <div class="22 hidden" id="video-library-content">
      <%# render file: 'users/video' %>
    </div>
  </div>
</div> -->