config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  # scope '(:locale)', locale: /fr/, default:  do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/, defaults: {locale: "en"} do
    root to: 'pages#home'

    devise_for :users, controllers: { registrations: 'registrations', confirmations: 'confirmations' }
    get 'confirm', to: 'pages#confirm'

    get 'about', to: 'pages#about'
    get 'contact', to: 'pages#contact'

    post '/subscribe', to: 'pages#subscribe'


    # Routes for core user side
    resources :users, only: [ :show, :edit, :update ] do

      # User Pages
      get 'profile', to: 'users#profile'
      get 'digital', to: 'users#digital'
      get 'children', to: 'users#children'
      get 'unlock', to: 'users#unlock'
      post 'unlock_data', to: 'users#unlock_data'
      resources :videos
      resources :call_to_action, controller: 'call_to_action', only: [:index, :new, :create, :edit, :update, :destroy]

      resources :notes
      resources :photos
      resources :references

      # Assignee Pages
      resources :assignees do
        get 'profile', to: 'assignees#profile'
        resources :notes
        resources :photos
        resources :references
      end

      # Approver Pages
      resources :approvers, controller: 'assignees', type: 'Approver' do
        # get 'notes', to: 'assignees#notes'
        # get 'references', to: 'assignees#references'
        # get 'photos', to: 'assignees#photos'
        # get 'video', to: 'assignees#video'
        get 'profile', to: 'assignees#profile'
        resources :notes, only: [:index, :new, :create, :edit, :update, :destroy]
        resources :photos, only: [:index, :show, :new, :create, :edit, :update, :destroy]
        resources :references, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      end

      # Guardian Pages
      resources :guardians, controller: 'assignees', type: 'Guardian' do
        get 'profile', to: 'assignees#profile'
        resources :notes, only: [:index, :new, :create, :edit, :update, :destroy]
        resources :photos, only: [:index, :show, :new, :create, :edit, :update, :destroy]
        resources :references, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      end

      # Recipient Pages
      resources :recipients, controller: 'assignees', type: 'Recipient' do
        get 'profile', to: 'assignees#profile'
        resources :notes, only: [:index, :new, :create, :edit, :update, :destroy]
        resources :photos, only: [:index, :show, :new, :create, :edit, :update, :destroy]
        resources :references, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      end

      # Routes for wizard sign-up
      resources :after_sign_up
    end
  end
end

app/models/admin_ref.rb
class Reference < ApplicationRecord
  belongs_to :reference_owner, polymorphic: true

  validates :title, presence: true
  validates :document, presence: true
end

app/models/approver.rb
class Approver < Assignee
  belongs_to :user
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :user
  belongs_to :assignee
end

app/models/assignee.rb
class Assignee < ApplicationRecord
  belongs_to :user

  has_many :notes, dependent: :destroy
  has_many :references, dependent: :destroy
  has_many :photos, dependent: :destroy

  has_attachment :profile_picture

  validates :first_name, presence: true
  validates :last_name, presence: true
  # validates :type, presence: true

  def full_name
    middle_name ? first_name + " " + middle_name + " " + last_name : first_name + " " + last_name
  end

  def name_surname
    first_name + " " + last_name
  end

  def details_completed?
    true if first_name && last_name && relationship && profile_picture && citizenship && date_of_birth && email && phone_number && address_line_1 && address_line_2 && city && postcode && country
  end

  def self.show_partner
    where('relationship = ?', 'Partner')
  end

  def self.show_children
    where('type = ? AND relationship = ?', 'Recipient', 'Child')
  end

  def self.show_other_family
    where('type = ? AND relationship != ? AND relationship != ? AND relationship != ?',
     'Recipient', 'Friend', 'Partner', 'Child')
  end

  def self.show_friends
    where('type = ? AND relationship = ?', 'Recipient', 'Friend')
  end
end

app/models/call_to_action.rb
class CallToAction < ApplicationRecord
  belongs_to :user
end

app/models/child.rb
class Child < Assignee
  belongs_to :user
end

app/models/guardian.rb
class Guardian < Assignee
  belongs_to :user
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true
end

app/models/partner.rb
class Partner < Assignee
  belongs_to :user
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user

  validates :title, presence: true

  has_attachment :photo
end

app/models/proof.rb
class Proof < ApplicationRecord
  belongs_to :user

  has_attachment :document

  validates :title, presence: true
  validates :document, presence: true
end

app/models/recipient.rb
class Recipient < Assignee
  belongs_to :user
end

app/models/reference.rb
class Reference < ApplicationRecord
  belongs_to :user

  validates :title, presence: true

  has_attachment :document
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_attachment :profile_picture

  has_many :assignees, dependent: :destroy
    has_many :guardians, dependent: :destroy
    has_many :recipients, dependent: :destroy
    has_many :approvers, dependent: :destroy
  has_many :proofs, dependent: :destroy
  has_many :notes, dependent: :destroy
  has_many :references, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :videos, dependent: :destroy
  has_one :call_to_action, dependent: :destroy

  # validates :email, uniqueness: true
  validates :title, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  accepts_nested_attributes_for :assignees

  def details_completed?
    true if first_name && last_name && profile_picture && citizenship && date_of_birth && email && phone_number && address_line_1 && address_line_2 && city && postcode && country
  end

  def full_name
    middle_name ? first_name + " " + middle_name + " " + last_name : first_name + " " + last_name
  end

  def name_surname
    first_name + " " + last_name
  end

  # Relationship Methods
  def partner
    recipients.where('relationship = ?', 'Partner').first
  end

  def children
    recipients.where('relationship = ?', 'Child')
  end

  def show_other
    recipients.where(['relationship != ? AND relationship != ?', 'Partner', 'Child'])
  end

  def show_other_family
    recipients.where('relationship != ? AND relationship != ? AND relationship != ?',
     'Friend', 'Partner', 'Child')
  end

  def show_mother
    recipients.where('relationship = ?', 'Mother')
  end

  def show_friends
    recipients.where('relationship = ?', 'Friend')
  end

  private

  # Data Unlock
  def self.send_unlock_email(user, recipients)
    UserMailer.unlock(user, recipients).deliver_now
  end

end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  # validates :video, presence: true

  has_attachment :video
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/proofs_helper.rb
module ProofsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-item">
    <h3 id="site-map">Site Map</h3>
    <div class="column-flex">
      <div class="site-column">
        <p>Home</p>
        <p>How it works</p>
        <p>Pricing</p>
        <p>About</p>
      </div>
      <div class="site-column">
        <p>Contact</p>
        <p>Careers</p>
        <p>Terms & Conditions</p>
        <p>Privacy Policy</p>
      </div>
    </div>
  </div>
  <div class="footer-item" id="find-us">
    <h3>Find Us</h3>
    <p>MyWill</p>
    <p>23a South End Road</p>
    <p>London NW3 2PT</p>
  </div>
  <div class="footer-item" id="disclaimer">
    <p>MyWill is an online service that provides digital storage services through a trusted infrastructure. We are not a law firm and are not a substitute for a lawyer's advice about complex family issues.</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag('logo.png', class: "logo") %>
  <% end %>

  <!-- Central Links -->
  <div class="navbar-center">
    <%= link_to t('About'), about_path, class: "navbar-text top-margin-navbar hidden-xs" %>
    <%= link_to root_path, class: "navbar-text i18n-button", "data-toggle":"dropdown" do %>
      <% if params[:locale] == 'fr' %>
        <%= image_tag('fr.png', class: "flag hidden-xxs") %>
        <%= t("French") %>
      <% else %>
        <%= image_tag('gb.png', class: "flag hidden-xxs") %>
        <%= t("English") %>
      <% end %>
      <i class="fa fa-caret-down dropdown-toggle"></i>
    <% end %>
    <%= link_to t('Contact'), contact_path, class: "navbar-text top-margin-navbar hidden-xs" %>
    <ul class="i18n dropdown-menu i18n-dropdown-menu">
      <li>
        <%= link_to url_for( locale: nil ) do %>
          <%= image_tag('gb.png', class: "flag") %>
          <%= t("English") %>
        <% end %>
      </li>
      <!-- <li> -->
        <%# link_to url_for( locale: 'fr' ) do %>
          <%# image_tag('fr.png', class: "flag") %>
          <%# t("French") %>
        <%# end %>
      <!-- </li> -->
    </ul>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Profile picture and dropdown -->
      <%= link_to user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" do %>
        <i class="fa fa-user"></i>
        <%= t('Profile') %>
      <% end %>
      <%= link_to t("Log out"), destroy_user_session_path, method: :delete, id: "login-button", class: " navbar-wagon-link btn btn-default" %>

    <% else %>

      <%= link_to t("Sign Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link btn btn-transparent" %>

    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-sm hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" do %>
              <i class="fa fa-user"></i>
              <%= t('Profile') %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete, class: " navbar-wagon-link" do %>
              <i class="fa fa-sign-out"></i>
              <%= t('Log out') %>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to t("Sign Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
          </li>
          <li>
            <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link btn btn-transparent" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_scrollmenu.html.erb
<div class="scrollmenu">
  <div class="scrollbox text-center" id="home-scrollbox">
    <div>
      <%= link_to user_path(current_user), class: "scrollmenu-link" do %>
        <h3><%= t('Home') %></h3>
      <% end %>
    </div>
    <div class="scrollitem <%= 'active' if params[:controller] == 'users' && params[:action] == 'show' %>">
      <%= link_to user_path(current_user), class: 'scrollmenu-me' do %>
        <div class="menu-icon">
          <i class="fa fa-home" aria-hidden="true"></i>
        </div>
        <h4><%= t('Profile') %></h4>
      <% end %>
    </div>
  </div>

<!--   <div class="scrollbox text-center">
    <div>
      <%# link_to user_path(current_user), class: "scrollmenu-link" do %>
        <h3><%# t('Me') %></h3>
      <# end %>
    </div>
    <div class="scrollitem <%# 'active' if params[:controller] == 'users' && params[:action] == 'show' %>">
      <%# link_to user_path(current_user), class: 'scrollmenu-me' do %>
        <%# if current_user.profile_picture %>
          <%# cl_image_tag(current_user.profile_picture.path, transformation: [{width: 70, height: 70, gravity: "face", radius: "max", crop: "fill"}]) %>
        <%# elsif @user.title == "Mr" %>
          <%# image_tag('male.png', class: "menu-icon") %>
        <%# else %>
          <%# image_tag('female.png', class: "menu-icon") %>
          <div class="menu-icon placeholder"></div>
        <%# end %>
        <h4><%= @user.first_name %></h4>
      <%# end %>
    </div>
  </div> -->

  <% if !@user.assignees.where('relationship = ?', 'Partner').empty? %>
    <div class="scrollbox text-center">
      <div>
        <%= link_to user_assignee_path(current_user, @user.partner.id), class: "scrollmenu-link partner-link" do %>
          <h3><%= t('Partner') %></h3>
        <% end %>
      </div>
      <% @user.assignees.where('relationship = ?', 'Partner').each do |recipient| %>
        <div class="scrollitem <%= 'active' if @recipient && @recipient.id == recipient.id %>">
          <%= link_to user_recipient_path(current_user, recipient), class: 'scrollmenu-partner' do %>
            <% if recipient.profile_picture %>
              <%= cl_image_tag(recipient.profile_picture.path, transformation: [{width: 70, height: 70, gravity: "face", radius: "max", crop: "fill"}]) %>
            <% elsif @user.title == "Mr" %>
              <%= image_tag('female.png', class: "menu-icon") %>
            <% else %>
              <%= image_tag('male.png', class: "menu-icon") %>
            <% end %>
            <h4><%= recipient.first_name %></h4>
            <h6><%= recipient.id %></h6>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>

  <% if !@user.children.empty? %>
    <div class="scrollbox">
      <div class="scrolltitle">
        <%= link_to '#', class: "scrollmenu-link children-link" do %>
          <h3><%=  t('Children') %></h3>
        <% end %>
        <%= link_to new_user_assignee_path(I18n.locale, current_user, 'Child'), class: "add-icon" do %>
          <i class="fa fa-plus" aria-hidden="true"><span class="add-tooltip"><%= t('Add Child') %></span></i>
        <% end %>
      </div>
      <% @user.children.each do |recipient| %>
        <div class="scrollitem <%= 'active' if @recipient && @recipient.id == recipient.id %>">
          <%= link_to user_recipient_path(current_user, recipient),class: 'scrollmenu-children' do %>
            <% if recipient.profile_picture %>
              <%= cl_image_tag(recipient.profile_picture.path, transformation: [{width: 70, height: 70, gravity: "face", radius: "max", crop: "fill"}]) %>
            <% elsif recipient.title == "Mrs" || recipient.title == "Ms" %>
              <%= image_tag('girl.png', class: "menu-icon") %>
            <% else %>
              <%= image_tag('boy.png', class: "menu-icon") %>
            <% end %>
            <h4><%= recipient.first_name %></h4>
            <h6><%= recipient.id %></h6>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>

  <% if !@user.guardians.empty? %>
    <div class="scrollbox">
      <div class="scrolltitle">
        <%= link_to '#', class: "scrollmenu-link guardian-link" do %>
          <h3><%= t('Guardians') %></h3>
        <% end %>
        <%= link_to new_user_assignee_path(I18n.locale, current_user, 'Guardian'), class: "add-icon" do %>
            <i class="fa fa-plus" aria-hidden="true"><span class="add-tooltip"><%= t('Add Guardian') %></span></i>
        <% end %>
      </div>
      <% @user.guardians.each do |guardian| %>
        <div class="scrollitem <%= 'active' if @guardian && @guardian.id == guardian.id %>">
          <%= link_to user_guardian_path(current_user, guardian), class: 'scrollmenu-guardians' do %>
            <% if guardian.profile_picture %>
              <%= cl_image_tag(guardian.profile_picture.path, transformation: [{width: 70, height: 70, gravity: "face", radius: "max", crop: "fill"}]) %>
            <% elsif guardian.title == "Mrs" || guardian.title == "Ms" %>
              <%= image_tag('guardian_female.png', class: "menu-icon") %>
            <% else %>
              <%= image_tag('guardian_male.png', class: "menu-icon") %>
            <% end %>
            <h4><%= guardian.first_name %></h4>
            <h6><%= guardian.id %></h6>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>

  <% if !@user.approvers.empty? %>
    <div class="scrollbox">
      <div class="scrolltitle">
        <%= link_to '#', class: "scrollmenu-link approver-link" do %>
          <h3><%= t('Approvers') %></h3>
        <% end %>
        <%= link_to new_user_assignee_path(I18n.locale, current_user, 'Approver'), class: "add-icon" do %>
            <i class="fa fa-plus" aria-hidden="true"><span class="add-tooltip"><%= t('Add Approver') %></span></i>
        <% end %>
      </div>
      <% @user.approvers.each do |approver| %>
        <div class="scrollitem <%= 'active' if @approver && @approver.id == approver.id %>">
          <%= link_to user_guardian_path(current_user, approver), class: 'scrollmenu-approvers' do %>
            <% if approver.profile_picture %>
              <%= cl_image_tag(approver.profile_picture.path, transformation: [{width: 70, height: 70, gravity: "face", radius: "max", crop: "fill"}]) %>
            <% elsif approver.title == "Mrs" || approver.title == "Ms" %>
              <%= image_tag('guardian_female.png', class: "menu-icon") %>
            <% else %>
              <%= image_tag('guardian_male.png', class: "menu-icon") %>
            <% end %>
            <h4><%= approver.first_name %></h4>
            <h6><%= approver.id %></h6>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>

  <% if !@user.show_other.empty? %>
    <div class="scrollbox">
      <div class="scrolltitle">
        <%= link_to '#', class: "scrollmenu-link recipient-link" do %>
          <h3><%= t('Other Friends & Family') %></h3>
        <% end %>
        <%= link_to new_user_assignee_path(I18n.locale, current_user, 'Other'), class: "add-icon" do %>
            <i class="fa fa-plus" aria-hidden="true"><span class="add-tooltip"><%= t('Add Recipient') %></span></i>
        <% end %>
      </div>
      <% @user.show_other.each do |recipient| %>
        <div class="scrollitem <%= 'active' if @recipient && @recipient.id == recipient.id %>">
          <%= link_to user_guardian_path(current_user, recipient), class: 'scrollmenu-recipients' do %>
            <% if recipient.profile_picture %>
              <%= cl_image_tag(recipient.profile_picture.path, transformation: [{width: 70, height: 70, gravity: "face", radius: "max", crop: "fill"}]) %>
            <% elsif recipient.title == "Mrs" || recipient.title == "Ms" %>
              <%= image_tag('guardian_female.png', class: "menu-icon") %>
            <% else %>
              <%= image_tag('guardian_male.png', class: "menu-icon") %>
            <% end %>
            <h4><%= recipient.first_name %></h4>
            <h6><%= recipient.id %></h6>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<% content_for(:after_js) do %>
  <script>
    // Clicking on assignee index links loads correct page and changes sidebar tab
    <% if params[:controller] == 'users' %>
      $('.children-link').click(function(e){
        e.preventDefault();
        $('.sidebar-tabs').children().removeClass("active");
        $('#recipient-sidebar-tab').addClass("active");
        $.ajax({
            type: "GET",
            url: <%= @user.id %> + "/children",
            data: { },
            success: function(data){
                $('#tab-content').empty().html(data);
            }
        });
      });
      $('.guardian-link').click(function(e){
        e.preventDefault();
        $('.sidebar-tabs').children().removeClass("active");
        $('#guardian-sidebar-tab').addClass("active");
        $.ajax({
            type: "GET",
            url: <%= @user.id %> + "/guardians",
            data: { },
            success: function(data){
                $('#tab-content').empty().html(data);
            }
        });
      });
      $('.approver-link').click(function(e){
        e.preventDefault();
        $('.sidebar-tabs').children().removeClass("active");
        $('#approver-sidebar-tab').addClass("active");
        $.ajax({
            type: "GET",
            url: <%= @user.id %> + "/approvers",
            data: { },
            success: function(data){
                $('#tab-content').empty().html(data);
            }
        });
      });
      $('.recipient-link').click(function(e){
        e.preventDefault();
        $('.sidebar-tabs').children().removeClass("active");
        $('#recipient-sidebar-tab').addClass("active");
        $.ajax({
            type: "GET",
            url: <%= @user.id %> + "/recipients",
            data: { },
            success: function(data){
                $('#tab-content').empty().html(data);
            }
        })
      });
    <% end %>
  </script>
<% end %>

app/views/shared/footers/_home_footer.html.erb
<div class="footer">
  <div class="footer-item">
    <h3 id="site-map"><%= t('Site Map') %></h3>
    <div class="column-flex">
      <div class="site-column">
        <%= link_to root_path do %>
          <p id="footer-home"><%= t('Home') %></p>
        <% end %>
        <%= link_to root_path + "#instructions" do %>
          <p id="footer-how"><%= t('How it works') %></p>
        <% end %>
      </div>
      <div class="site-column">
        <%= link_to contact_path do %>
          <p id="footer-contact"><%= t('Contact') %></p>
        <% end %>
        <%= link_to root_path + "#comparison" do %>
          <p id="footer-price"><%= t('Pricing') %></p>
        <% end %>
        <!-- <p id="footer-careers"><%= t('Careers') %></p> -->
        <!-- <p id="footer-terms"><%= t('Terms & Conditions') %></p> -->
      </div>
    </div>
  </div>
  <div class="footer-item" id="find-us">
    <h3><%= t('Find Us') %></h3>
    <p>IglooWorld LTD</p>
    <p>23a South End Road</p>
    <p>London NW3 2PT</p>
  </div>
  <div class="footer-item" id="disclaimer">
    <p><%= t('footer description') %></p>
  </div>
</div>