config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  # scope '(:locale)', locale: /fr/, default:  do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/, defaults: {locale: "en"} do
    root to: 'pages#home'

    devise_for :users, controllers: { registrations: 'registrations', confirmations: 'confirmations' }
    get 'confirm', to: 'pages#confirm'

    get 'about', to: 'pages#about'
    get 'contact', to: 'pages#contact'

    post '/subscribe', to: 'pages#subscribe'


    # Routes for core user side
    resources :users, only: [ :show, :edit, :update ] do

      # User Pages
      get 'profile', to: 'users#profile'
      get 'digital', to: 'users#digital'
      get 'children', to: 'users#children'
      get 'unlock', to: 'users#unlock'
      post 'unlock_data', to: 'users#unlock_data'
      resources :videos
      resources :call_to_action, controller: 'call_to_action', only: [:index, :new, :create, :edit, :update, :destroy]

      resources :notes
      resources :photos
      resources :references

      # Assignee Pages
      resources :assignees do
        get 'profile', to: 'assignees#profile'
        resources :notes
        resources :photos
        resources :references
      end

      # Approver Pages
      resources :approvers, controller: 'assignees', type: 'Approver' do
        # get 'notes', to: 'assignees#notes'
        # get 'references', to: 'assignees#references'
        # get 'photos', to: 'assignees#photos'
        # get 'video', to: 'assignees#video'
        get 'profile', to: 'assignees#profile'
        resources :notes, only: [:index, :new, :create, :edit, :update, :destroy]
        resources :photos, only: [:index, :show, :new, :create, :edit, :update, :destroy]
        resources :references, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      end

      # Guardian Pages
      resources :guardians, controller: 'assignees', type: 'Guardian' do
        get 'profile', to: 'assignees#profile'
        resources :notes, only: [:index, :new, :create, :edit, :update, :destroy]
        resources :photos, only: [:index, :show, :new, :create, :edit, :update, :destroy]
        resources :references, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      end

      # Recipient Pages
      resources :recipients, controller: 'assignees', type: 'Recipient' do
        get 'profile', to: 'assignees#profile'
        resources :notes, only: [:index, :new, :create, :edit, :update, :destroy]
        resources :photos, only: [:index, :show, :new, :create, :edit, :update, :destroy]
        resources :references, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      end

      # Routes for wizard sign-up
      resources :after_sign_up
    end
  end
end

app/models/assignee.rb
class Assignee < ApplicationRecord
  belongs_to :user

  has_many :notes, dependent: :destroy
  has_many :references, dependent: :destroy
  has_many :photos, dependent: :destroy

  has_attachment :profile_picture

  validates :first_name, presence: true
  validates :last_name, presence: true
  # validates :type, presence: true

  def full_name
    middle_name ? first_name + " " + middle_name + " " + last_name : first_name + " " + last_name
  end

  def name_surname
    first_name + " " + last_name
  end

  def details_completed?
    true if first_name && last_name && relationship && profile_picture && citizenship && date_of_birth && email && phone_number && address_line_1 && address_line_2 && city && postcode && country
  end

  def self.show_partner
    where('relationship = ?', 'Partner')
  end

  def self.show_children
    where('type = ? AND relationship = ?', 'Recipient', 'Child')
  end

  def self.show_other_family
    where('type = ? AND relationship != ? AND relationship != ? AND relationship != ?',
     'Recipient', 'Friend', 'Partner', 'Child')
  end

  def self.show_friends
    where('type = ? AND relationship = ?', 'Recipient', 'Friend')
  end
end

app/controllers/assignees_controller.rb
class AssigneesController < ApplicationController
  protect_from_forgery except: :new
  before_action :set_assignee, only: [:show, :edit, :update, :destroy]
  before_action :set_assignee_id, only: [:profile, :notes, :references, :photos, :videos]
  before_action :set_type


  def index
    # @assignees = Assignee.all
    @assignees = policy_scope(Assignee)
  end

  def show
    @user = User.where('id = ?', params[:user_id]).first
    authorize @assignee
  end

  def new
    @assignee = Assignee.new
    if params[:format] == 'Partner' || params[:format] == 'Child'
      @assignee.address_line_1 = @user.address_line_1
      @assignee.address_line_2 = @user.address_line_2
      @assignee.city = @user.city
      @assignee.postcode = @user.postcode
      @assignee.country = @user.country
    end

    authorize @assignee
  end

  def create
    @assignee = current_user.assignees.build(assignee_params)
    authorize @assignee
    if @assignee.save
      respond_to do |format|
        format.js
        format.html {
          redirect_to user_path(current_user)
        }
      end
    else
      respond_to do |format|
        format.js
        format.html { render :new }
      end
    end
  end

  def edit
    authorize @assignee
  end

  def update
    authorize @assignee
    if @assignee.update(assignee_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    authorize @assignee
    redirect_to user_path(current_user)
  end

  def profile
    authorize @user
  end

  def notes
    authorize @assignee
    @note = Note.new
  end

  def references
    authorize @assignee
    @reference = Reference.new
  end

  def photos
    authorize @assignee
    @photo = Photo.new
  end

  # def videos
  # end

  private

  def set_assignee
    @assignee = Assignee.find(params[:id])
  end

  def set_assignee_id
    @assignee = Assignee.find(params[:assignee_id] || params[:guardian_id] || params[:recipient_id])
  end

  def set_type
    if params[:type]
      @type = params[:type]
    elsif params[:format]
      @type = params[:format]
    end
  end

  def type
    params[:type]
  end

  def assignee_params
    params.require(type ? type.downcase.to_sym : :assignee).permit(:title, :first_name,
      :middle_name, :last_name, :citizenship, :date_of_birth, :email, :phone_number,
      :address_line_1, :address_line_2, :city, :country, :postcode, :relationship,
      :profile_picture, :type)
  end
end

app/helpers/assignees_helper.rb
module AssigneesHelper

  # Returns a dynamic path based on the provided parameters
  def sti_assignee_path(type = "assignee", assignee = nil, action = nil)
    send "#{format_sti(action, type, assignee)}_path", assignee
  end

  def format_sti(action, type, assignee)
    action || assignee ? "#{format_action(action)}#{type.underscore}" : "#{type.underscore.pluralize}"
  end

  def format_action(action)
    action ? "#{action}_" : ""
  end

end

app/views/assignees/_children_index.html.erb
<br>

<div class="container-box">
  <div class="header-box">
    <h2>My Children</h2>
    <%= link_to "Add Child", new_user_assignee_path(current_user, @type), class: "btn orange-button" %>
  </div>

  <div class="assignees">
    <% @user.assignees.where('relationship = ?', 'Child').each do |assignee| %>
      <div class="col-xs-12 col-md-6 col-lg-4">
        <div class="card">
          <%= link_to user_assignee_path(current_user, assignee.id) do %>
            <%= assignee.profile_picture ? cl_image_tag(assignee.profile_picture.path, transformation: [{width: 100, height: 100, gravity: "face", radius: "max", crop: "fill"}], class: "avatar-card push-right") : image_tag('user3.png', class: "avatar-card push-right") %>
            <div class="card-description">
              <h5 class="black-text"><strong><%= assignee.name_surname %></strong></h5>
              <%= link_to "View", user_assignee_path(current_user, assignee.id), class: "btn btn-info btn-default btn-ice reference-link" %>
              <%= link_to "Delete", user_assignee_path(current_user, assignee.id), data: {confirm: 'Are you sure?'}, method: :delete, class: "btn btn-danger btn-default" %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/assignees/_core_index.html.erb
<div class="container-box">
  <div class="header-box padding-15">
    <h2>My <%= @type.capitalize %>s</h2>
    <%= link_to t("Add New") + " " + @type, new_user_assignee_path(current_user, @type), class: "btn orange-button" %>
  </div>

  <div class="blue-box side-margin-small">
    <p><%= t('guardian explanation') %></p>
  </div>

  <div class="assignees">
    <% @assignees.where('type = ?', @type).each do |assignee| %>
      <div class="col-xs-12 col-md-6 col-lg-4">
        <div class="card">
          <%= link_to user_assignee_path(current_user, assignee.id) do %>
            <div class="card-buttons">
              <%= link_to user_assignee_path(current_user, note.assignee_id), data: {confirm: t('Are you sure')}, method: :delete do %>
                <i class="fa fa-trash" aria-hidden="true"></i>
              <% end %>
            </div>
            <% if assignee.profile_picture %>
              <%= cl_image_tag(assignee.profile_picture.path, transformation: [{width: 100, height: 100, gravity: "face", radius: "max", crop: "fill"}], class: "avatar-card push-right") %>
            <% elsif assignee.title == "Mrs" || assignee.title == "Ms" %>
              <%= image_tag('guardian_female.png', class: "index-icon") %>
            <% else %>
              <%= image_tag('guardian_male.png', class: "index-icon") %>
            <% end %>
            <div class="card-description">
              <h5 class="black-text"><strong><%= assignee.name_surname %></strong></h5>
              <%= link_to t("Delete"), user_assignee_path(current_user, assignee.id), data: {confirm: 'Are you sure?'}, method: :delete, class: "btn btn-danger btn-default" %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/assignees/create.js.erb
<% if @assignee.persisted? %>
  console.log('Assignee create')
  // Remove current tab content
  $('.container-box').remove()

  // Add form to tab content
  $('#tab-content').html("<%= j render file: 'assignees/index', type: @assignee.type %>");
<% else %>
  console.log('Assignee create fail')
  $('#tab-content').html("<%= j render 'assignees/form', user: @user, assignee: @assignee %>");
<% end %>

app/views/assignees/index.html.erb
<% content_for(:navbar) do %>
  <%= render 'shared/navbar' %>
<% end %>

<div class="dashboard-box" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.2) 50%), url(<%= asset_path('background.jpg') %>)">
  <div id="tab-content">
    <br>
    <div class="container-box">
      <div class="header-box padding-15">
        <h2>My <%= @type.capitalize %>s</h2>
        <%= link_to t("Add New") + " " + @type, new_user_assignee_path(I18n.locale, current_user, @type), class: "btn orange-button" %>
      </div>

      <div class="blue-box side-margin-small top-margin">
        <p><%= t('guardian explanation') %></p>
      </div>

      <div class="assignees">
        <% @assignees.where('type = ?', @type).each do |assignee| %>
          <div class="col-xs-12 col-md-6 col-lg-4">
            <div class="card relative">
              <div class="card-buttons">
                <%= link_to user_assignee_path(current_user, assignee.id), data: {confirm: t('Are you sure')}, method: :delete do %>
                  <i class="fa fa-trash" aria-hidden="true"></i>
                <% end %>
              </div>
              <%= link_to user_assignee_path(current_user, assignee.id) do %>
                <% if assignee.profile_picture %>
                  <%= cl_image_tag(assignee.profile_picture.path, transformation: [{width: 100, height: 100, gravity: "face", radius: "max", crop: "fill"}], class: "avatar-card push-right") %>
                <% elsif assignee.title == "Mrs" || assignee.title == "Ms" %>
                  <%= image_tag('guardian_female.png', class: "index-icon") %>
                <% else %>
                  <%= image_tag('guardian_male.png', class: "index-icon") %>
                <% end %>
                <div class="card-description">
                  <%= link_to user_assignee_path(current_user, assignee.id) do %>
                    <h5 class="black-text"><strong><%= assignee.name_surname %></strong></h5>
                    <h7 class="black-text"><%= assignee.try(:relationship) %></h7>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/assignees/new.html.erb
<% content_for(:navbar) do %>
  <%= render 'shared/navbar' %>
<% end %>

<% content_for(:sidebar) do %>
  <%= render 'shared/sidebars/sidebar_core' %>
<% end %>

<div class="dashboard-box" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.2) 50%), url(<%= asset_path('background.jpg') %>)">
  <div id="tab-content">
    <div class="container">
      <br>
      <div class="grey-box relative">
        <% if params[:format] == 'Guardian' || params[:type] == 'Guardian' || params[:assignee] && params[:assignee]['type'] == 'Guardian' %>
          <h3 class="new-title"><%= t('New Guardian') %></h3>
        <% elsif params[:format] == 'Approver' || params[:type] == 'Approver' %>
          <h3 class="new-title"><%= t('New Approver') %></h3>
        <% elsif params[:format] == 'Partner' || params[:relationship] == 'Partner' %>
          <h3 class="new-title"><%= t('New Partner') %></h3>
        <% elsif params[:format] == 'Child' || params[:relationship] == 'Child' %>
          <h3 class="new-title"><%= t('New Child') %></h3>
        <% else %>
          <h3 class="new-title"><%= t('New Recipient') %></h3>
        <% end %>
        <%= render 'assignees/form' %>
      </div>
    </div>
  </div>
</div>

<%= content_for(:after_js) do %>
  <script src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=<%= ENV['GOOGLE_API_BROWSER_KEY'] %>"></script>
  <script>
    // Changes to relevant sidebar tab
    $('.sidebar-tabs').children().removeClass("active");
    console.log('<%= params[:format] %>');
    if ('<%= params[:format] %>' == 'Guardian' || '<%= params[:format] %>' == 'Approver') {
      $('#<%= params[:format].downcase %>-sidebar-tab').addClass("active");
    } else {
      $('#recipient-sidebar-tab').addClass("active");
    }
  </script>
<% end %>

app/views/assignees/profile.html.erb
<div class="container">
  <br>
  <div class="grey-box relative">
    <br>
    <%= link_to '#', class: 'profile-picture-inline' do %>

      <% if @assignee.profile_picture %>
        <%= cl_image_tag(@assignee.profile_picture.path, transformation: [{width: 120, height: 120, gravity: "face", radius: "max", crop: "fill"}], class: "avatar-edit") %>
      <% elsif @assignee.relationship == 'Partner' %>
        <% if @user.title == "Mr" %>
          <%= image_tag('female.png', class: "edit-icon") %>
        <% else %>
          <%= image_tag('male.png', class: "edit-icon") %>
        <% end %>
      <% elsif %>
        <% if @assignee.relationship == "Child"%>
          <%= image_tag('girl.png', class: "edit-icon") %>
        <% else %>
          <%= image_tag('boy.png', class: "edit-icon") %>
        <% end %>
      <% else %>
        <% if @assignee.title == "Mrs" || @assignee.title == "Ms" %>
          <%= image_tag('guardian_female.png', class: "edit-icon") %>
        <% else %>
          <%= image_tag('guardian_male.png', class: "edit-icon") %>
        <% end %>
      <% end %>

      <p><%= t('Change Picture') %></p>
      <%= simple_form_for [current_user, @assignee], html: {class: 'form-inline edit-profile-picture invisible'} do |f| %>
        <%= f.input :profile_picture, as: :attachinary, label: false, input_html: { class: 'profile-upload'} %>
        <%= f.submit t("Upload"), class: 'profile-upload'  %>
      <% end %>
    <% end %>

    <% if params[:format] == 'Guardian' || @assignee.type == 'Guardian' %>
      <h3 class="new-title padding-15">Guardian</h3>
    <% elsif params[:format] == 'Approver' || @assignee.type == 'Approver' %>
      <h3 class="new-title padding-15">Approver</h3>
    <% elsif params[:relationship] == 'Partner' || @assignee.relationship == 'Partner' %>
      <h3 class="new-title padding-15">Partner</h3>
    <% elsif params[:relationship] == 'Child' || @assignee.relationship == 'Child' %>
      <h3 class="new-title padding-15">Child</h3>
    <% else %>
      <h3 class="new-title padding-15"><%= @assignee.relationship %></h3>
    <% end %>

    <hr>
    <div class="profile-header">
      <%= link_to t("Details"), '#' %>
      <div class="profile-controls">
        <%= link_to "Edit", '#', id: "view-details" %>
      </div>
    </div>
    <div class="profile-details">
      <p class="name-tag"><%= @assignee.try(:name_surname) %></p>

      <div class="row">
        <div class="col-xs-12 col-lg-6">
          <% if @assignee.citizenship %>
            <p><span class="category-tag"><%= t('Citizenship') %></span><%= ": " + @assignee.citizenship + " " + t('Citizen') %></p>
          <% end %>

          <% if @assignee.date_of_birth && @assignee.date_of_birth != "" %>
            <p><span class="category-tag"><%= t('DoB') %></span><%= ": " + @assignee.date_of_birth %></p>
          <% end %>

          <% if @assignee.email && @assignee.email != "" %>
            <p><span class="category-tag"><%= t('Email')%></span><%= ": " + @assignee.email %></p>
          <% end %>
        </div>
        <div class="col-xs-12 col-lg-6">
          <% if @assignee.phone_number && @assignee.phone_number != "" %>
            <p><span class="category-tag"><%= t('Phone Number') %></span><%= ": " + @assignee.phone_number %></p>
          <% end %>

          <% if @assignee.address_line_1 && @assignee.address_line_1 != "" %>
            <p><span class="category-tag"><%= t('Address') %></span><%= ": " + @assignee.address_line_1 %><%= ", " + @assignee.address_line_2 if @assignee.address_line_2 %></p>
            <p><%= @assignee.try(:city) %><%= ", " + @assignee.postcode if @assignee.postcode %><%= ", " + @assignee.country if @assignee.country %></p>
          <% else %>
            <p class="notice-text"><%= t('address required') %></p>
          <% end %>
        </div>
      </div>
    </div>

    <hr>
    <div class="profile-header">
      <div>
        Notes
        <%= link_to new_user_assignee_note_path(I18n.locale, current_user.id, @assignee, @note), remote: true, id: "add-note" do %>
          <i class="fa fa-plus" aria-hidden="true"><span class="add-tooltip"><%= t('Add Note') %></span></i>
      <% end %>
      </div>
      <div class="profile-controls">
        <%= link_to "View All >>", '#', id: "view-notes" %>
      </div>
    </div>
    <div class="profile-form hidden">
      <i class="fa fa-times" aria-hidden="true"></i>
      <div class="note-form hidden" id="new-note-form"></div>
    </div>
    <% @assignee.notes.each do |note| %>
      <div class="profile-content">
        <div>
          <h5><%= note.title %></h5>
          <p><%= note.created_at.strftime("Created on  %d/%m/%Y") %></p>
        </div>
        <div class="profile-controls">
          <%= link_to edit_user_assignee_note_path(current_user, note.assignee_id, note.id), remote: true do %>
            <i class="fa fa-pencil" aria-hidden="true"> </i>
          <% end %>
          <%= link_to user_note_path(current_user, note.id), data: {confirm: t('Are you sure')}, method: :delete do %>
            <i class="fa fa-trash" aria-hidden="true"></i>
          <% end %>
        </div>
      </div>
      <div class="profile-form hidden">
        <i class="fa fa-times" aria-hidden="true"></i>
        <div class="note-form hidden" id="edit-note-form-<%= note.id %>"></div>
      </div>
    <% end %>

    <hr>
    <div class="profile-header">
      <div>
        Photos
        <%= link_to new_user_assignee_photo_path(I18n.locale, current_user.id, @assignee, @photo), remote: true, id: "add-photo" do %>
          <i class="fa fa-plus" aria-hidden="true"><span class="add-tooltip"><%= t('Add Photo') %></span></i>
      <% end %>
      </div>
      <div class="profile-controls">
        <%= link_to "View All >>", '#', id: "view-photos" %>
      </div>
    </div>
    <div class="profile-form hidden">
      <i class="fa fa-times" aria-hidden="true"></i>
      <div class="photo-form hidden" id="new-photo-form"></div>
    </div>
    <% @assignee.photos.each do |photo| %>
      <div class="profile-content">
        <div>
          <h5><%= photo.title %></h5>
          <p><%= photo.created_at.strftime("Created on  %d/%m/%Y") %></p>
        </div>
        <div class="profile-controls">
          <%= link_to edit_user_assignee_photo_path(current_user, photo.assignee_id, photo.id), remote: true do %>
            <i class="fa fa-pencil" aria-hidden="true"> </i>
          <% end %>
          <%= link_to user_photo_path(current_user, photo.id), data: {confirm: t('Are you sure')}, method: :delete do %>
            <i class="fa fa-trash" aria-hidden="true"></i>
          <% end %>
        </div>
      </div>
      <div class="profile-form hidden">
        <i class="fa fa-times" aria-hidden="true"></i>
        <div class="photo-form hidden" id="edit-photo-form-<%= photo.id %>"></div>
      </div>
    <% end %>

    <hr>
    <div class="profile-header">
      <div>
        Admin References
        <%= link_to new_user_assignee_reference_path(I18n.locale, current_user.id, @assignee, @reference), remote: true, id: "add-reference" do %>
          <i class="fa fa-plus" aria-hidden="true"><span class="add-tooltip"><%= t('Add Reference') %></span></i>
      <% end %>
      </div>
      <div class="profile-controls">
        <%= link_to "View All >>", '#', id: "view-references" %>
      </div>
    </div>
    <div class="profile-form hidden">
      <i class="fa fa-times" aria-hidden="true"></i>
      <div class="reference-form hidden" id="new-reference-form"></div>
    </div>
    <% @assignee.references.each do |reference| %>
      <div class="profile-content">
        <div>
          <h5><%= reference.title %></h5>
          <p><%= reference.created_at.strftime("Created on  %d/%m/%Y") %></p>
        </div>
        <div class="profile-controls">
          <%= link_to edit_user_assignee_reference_path(current_user, reference.assignee_id, reference.id), remote: true do %>
            <i class="fa fa-pencil" aria-hidden="true"> </i>
          <% end %>
          <%= link_to user_reference_path(current_user, reference.id), data: {confirm: t('Are you sure')}, method: :delete do %>
            <i class="fa fa-trash" aria-hidden="true"></i>
          <% end %>
        </div>
      </div>
      <div class="profile-form hidden">
        <i class="fa fa-times" aria-hidden="true"></i>
        <div class="reference-form hidden" id="edit-reference-form-<%= reference.id %>"></div>
      </div>
    <% end %>

    <hr>
    <br>

  </div>
</div>

<% content_for(:after_js) do %>
  <script>
    /* Cancel add/edit form */
    $('.fa-times').on('click', function() {
      $(this).parent().addClass('hidden');
    });
    /* View all leads to correct tab */
    $('#view-details').click(function(e){
      e.preventDefault();
      $('.sidebar-tabs').children().removeClass("active");
      $('#show-details-sidebar-tab').addClass('active');
      $.ajax({
          type: "GET",
          url: <%= @assignee.id %> + "/edit",
          data: { },
          success: function(data){
              $('#tab-content').empty().html(data);
          }
      });
    });
    $('#view-notes').click(function(e){
      e.preventDefault();
      $('.sidebar-tabs').children().removeClass("active");
      $('#show-notes-sidebar-tab').addClass('active');
      $.ajax({
          type: "GET",
          url: <%= @assignee.id %> + "/notes",
          data: { },
          success: function(data){
              $('#tab-content').empty().html(data);
          }
      });
    });
    $('#view-photos').click(function(e){
      e.preventDefault();
      $('.sidebar-tabs').children().removeClass("active");
      $('#show-photos-sidebar-tab').addClass('active');
      $.ajax({
          type: "GET",
          url: <%= @assignee.id %> + "/photos",
          data: { },
          success: function(data){
              $('#tab-content').empty().html(data);
          }
      });
    });
    $('#view-references').click(function(e){
      e.preventDefault();
      $('.sidebar-tabs').children().removeClass("active");
      $('#show-admin-sidebar-tab').addClass('active');
      $.ajax({
          type: "GET",
          url: <%= @assignee.id %> + "/references",
          data: { },
          success: function(data){
              $('#tab-content').empty().html(data);
          }
      });
    });
  </script>
<% end %>

app/views/assignees/references.html.erb
<% content_for(:navbar) do %>
  <%= render 'shared/navbar' %>
<% end %>

<div class="container">
  <br>

  <% if !@assignee.references.empty? %>
    <div class="header-box padding-15">
      <h2><%= t('Admin & Reference Documents') %></h2>
      <%= link_to t("Add Reference"), new_user_reference_path([I18n.locale, current_user, @assignee, @reference]), remote: true, class: "btn orange-button", id: "add-reference" %>
    </div>

    <div class="blue-box detail-box side-margin-small top-margin">
      <p><%= t('note description html') %></p>
    </div>

    <div class="col-xs-12 col-md-6 invisible">
      <div class="note-card">
        <div class="reference-form" id="new-reference-form"></div>
      </div>
    </div>

    <% @assignee.references.reverse.each do |reference| %>
      <div class="col-xs-12 col-sm-6">
        <div class="note-card">
          <div class="card-buttons">
            <%= link_to user_assignee_reference_path(current_user, reference.assignee_id, reference), remote: true do %>
              <i class="fa fa-pencil" aria-hidden="true"> </i>
            <% end %>
            <%= link_to user_assignee_reference_path(current_user, reference.assignee_id, reference.id), data: {confirm: t('Are you sure')}, method: :delete do %>
              <i class="fa fa-trash" aria-hidden="true"></i>
            <% end %>
          </div>
          <div class="note-spacing" id="assignee-reference-<%= reference.id %>">
            <div class="note-title">
              <h4><strong><%= reference.title %></strong></h4>
              <h5><strong>For:</strong> <%= Assignee.find(reference.assignee_id).first_name %></h5>
            </div>
            <hr>
            <br>
            <%= link_to user_assignee_reference_path(current_user, reference.assignee_id, reference), class: "reference-link", "data-reference-id" => reference.id, "data-assignee-id" => reference.assignee_id do %>
              <%= cl_image_tag(reference.document_seed, width: 200, height: 150) %>
            <% end %>
            <div class="card-content card-overflow">
              <p><%= reference.comments %></p>
            </div>
          </div>
          <div class="reference-form" id="edit-reference-form-<%= reference.id %>"></div>
        </div>
      </div>
    <% end %>

  <% else %>

    <div class="side-margin white-text">
      <h2>References</h2>

      <div class="blue-box">
        <p><%= t('note description html') %></p>
      </div>
    </div>

    <div class="grey-box">
      <h5><strong><%= t('not added notes') %></strong></h5>
      <p><%= t('please use form below') %></p>
      <%= simple_form_for([@user, @assignee, @reference]) do |f| %>
        <%= f.hidden_field :assignee_id, value: @assignee.id %>
        <%= f.input :title, label: t('Title') %>
        <%= f.input :comments, label: t('Content') %>
        <div class="submit-button text-center">
          <%= f.button :submit, t("Create"), class: "btn purple-button" %>
        </div>
      <% end %>
    </div>

  <% end %>
</div>

<% content_for(:after_js) do %>
  <script>
    // Clicking on reference loads relevant show page
    $('.reference-link').click(function(e){
      e.preventDefault();
      var referenceId = $(this).data('reference-id');
      var assigneeId = $(this).data('assignee-id');
      var userId = <%= @user.id %>;
      $('#tab-content').empty();
      $.ajax({
          type: "GET",
          url: "/users/" + userId + "/assignees/" + assigneeId + "/references/" + referenceId,
          data: { },
          success: function(data){
              $('#tab-content').empty().html(data);
          }
      });
    });
  </script>
<% end %>